### PR TITLE
Fix/issue 96

### PR DESCRIPTION
**Pull request by donnapep**
* Add PUD failover setting.
* Rename e2e tests to integration tests.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep I think your default env setting in the gulp file should be `prod`, looks like your `dist/` files are built for `dev`

**Comment by donnapep** [comment]
@stulees Thanks. Updated and one additional minor change. Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
