### PR TITLE
updates hoek dependency to fix known vulnerability

### PR DESCRIPTION
**Pull request by pcsandford**
@jungeunyoon @stulees @Rise-Vision/content updating hoek dependency to fix security vulnerability. 

I noticed that two other files were generated locally, `dist/js/widget.js` and `dist/js/widget.min.js`, as it looks like they are picking up the change Rodrigo made to the timeout in the src folder in the previous PR. I have not committed these but let me know if I should.

Thanks!

### CODE REVIEW

**Comment by jungeunyoon** [comment]
@pcsandford Nice catch! I know it isn't part of this card but would you mind creating a new PR for those `dist` files please?

**Comment by stulees** [comment]
@pcsandford @jungeunyoon Just and FYI, those dist/ files aren't required and they're being generated only because this repo doesn't .gitignore them and still commits the entire dist/ directory. This widget/repo missed a technical debt epic and thus isn't consistent with the rest of the core widgets which we stopped committing the dist/ folder for.

**Comment by jungeunyoon** [comment]
@stulees @pcsandford mmm makes sense. pretty sure i've seen a few other repos that include it as well. another thing to add to the list of improvements post-defects. thanks!

**Comment by stulees** [comment]
@jungeunyoon Specifically core widget repos should not be committing dist/ to github as it is unnecessary and causes bloated PRs. 

I'm pretty sure all our core widgets do not commit it except for this one. Cheers

**Pull request merged**
