### PR TITLE
Chore/hide completed events

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Will need to rebase afterwards.

Also, this is a prime example of needing the ability to supply different mock data. I've tried different things, but can't find a good way to change the `showEnd` parameter to test all its different values, redraw the UI, and then test that the times are displayed correctly. So there's very little test coverage for this change.

Thx.

**Comment by stulees** [comment]
@donnapep Okay re: test coverage. :+1:

**Comment by donnapep** [comment]
@stulees I think I'm going to take the E2E Test Coverage Improvements - Multiple mock-data files card now. I have more changes coming up that will be untestable if this doesn't get resolved. Thx.

**Comment by stulees** [comment]
@donnapep Okay sounds like a good idea to make it higher priority then. If you want to discuss different approaches let me know. Thanks

**Comment by donnapep** [comment]
@stulees OK, so I ended up being able to leverage functionality available already in CasperJS, namely `casper.options.clientScripts` in order to dynamically pass in different mock data files. I've completely restructured the Widget's e2e tests. Since I didn't need to do the same thing for the settings, I didn't spend time figuring out how to do it there as well. We can cross that bridge if and when we come to it.

There are some changes that needed to be made to the Gulpfile. Unfortunately, it's a little more complicated now because it has to include mock data for e2e:settings but not for e2e:widget, since that gets dynamically passed in as part of the scenarios.

Let me know if you have any questions. Thx.

**Comment by stulees** [comment]
@donnapep Nice! `casper.options.clientScripts` looks like it was exactly what we needed. I somewhat doubt we'll ever really need to dynamically use different mock-data for settings, but agreed, cross that bridge if/when we come to it. 

My only suggestion is to split up your `widget-scenarios.js` into different files (based on which mock data is used). The file as it is now is pretty long and the infrastructure is there for having multiple files instead. Thanks

**Comment by donnapep** [comment]
@stulees Funny, I thought of splitting the test files up after I submitted the PR. Let me do that now.

**Comment by donnapep** [comment]
@stulees What do you think of this naming convention? I did away with tacking `scenarios` on the end since it's not needed and just makes everything that much longer. Thx.

**Comment by stulees** [comment]
@donnapep I think it's okay, can be personal preference because we do have widget-tester use the default for e2e settings (eg. http://goo.gl/IId55B) if nothing is defined in our task. Speaking of which, I think you might be able to omit `testFiles: "test/e2e/widget-*.js"` for e2e widget due to this line of code in widget-tester http://goo.gl/S4dMc8

**Comment by donnapep** [comment]
@stulees I actually can't do that because it will pick up my settings files for the widget tests.

**Comment by stulees** [comment]
@donnapep Ah right, okay. Looks good :+1:

**Pull request merged**
